#!/bin/sh /etc/rc.common
  
START=96
  
SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
  
start() {
    if ! ipset -q list iptv >/dev/null; then
        ipset create iptv nethash
    fi
    service_start /root/easyiptv/easyiptv.sh
}
  
stop() {
    service_stop /root/easyiptv/easyiptv.sh
    ipset flush iptv
    killall logread
}
